spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.113.216.99:3306/FinancialManagement
mybatis:
  config-location: classpath:mybatis/mybatis-confi.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
